In [27]:
import numpy as np
from scipy.optimize import linprog
import cvxpy as cp

In [45]:
# nash using lp formulation


#  payoff matrix for Player A
A = np.array([
    [1, -1],
    [-1, 1]
])
B = -A


m, n = A.shape

# Objective function: maximize v
c = np.zeros(m + 1)
c[-1] = -1  # We want to maximize v, which is equivalent to minimizing -v

# Inequality constraints: sum(A[i, j] * x_i) >= v for all j
A_ub = np.zeros((n, m + 1))
for j in range(n):
    A_ub[j, :-1] = B[:, j]
    A_ub[j, -1] = 1

b_ub = np.zeros(n)

# Equality constraints: sum(x_i) = 1
A_eq = np.ones((1, m + 1))
A_eq[0, -1] = 0
b_eq = np.array([1])

# Bounds for variables: x_i >= 0 and v is free
bounds = [(0, None) for _ in range(m)] + [(None, None)]

# Solve the linear program
result = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=bounds, method='highs')

# Extract the mixed strategy and game value

x = result.x[:-1]
v = result.x[-1]

print("Optimal mixed strategy for Player A:", x)
print("Value of the game:", v)

Optimal mixed strategy for Player A: [0.5 0.5]
Value of the game: -0.0


In [29]:
import cvxpy as cp


A = np.array([[0, 1, -1], [-1, 0, 1], [1, -1, 0]])

B = -A




m, n = A.shape

# Define variables
pi = cp.Variable((m, n), nonneg=True)

# Constraints
constraints = [cp.sum(pi) == 1]

for i in range(m):
    for i_prime in range(m):
        if i != i_prime:
            constraints.append(cp.sum(pi[i, :] * (A[i, :] - A[i_prime, :])) >= 0)

for j in range(n):
    for j_prime in range(n):
        if j != j_prime:
            constraints.append(cp.sum(pi[:, j] * (B[:, j] - B[:, j_prime])) >= 0)

# Define the objective function (maximize the sum of expected payoffs)
objective = cp.Maximize(cp.sum(cp.multiply(pi, A + B)))

# Solve the problem
problem = cp.Problem(objective, constraints)
problem.solve()

print("Correlated Equilibrium joint distribution (zero-sum):")
print(pi.value)

Correlated Equilibrium joint distribution (zero-sum):
[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]


C:\Users\Mazi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cvxpy\expressions\expression.py:650: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 93 times so far.

  warnings.warn(msg, UserWarning)
C:\Users\Mazi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cvxpy\expressions\expression.py:650: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-ma

In [5]:
import cvxpy as cp

A = np.array([
    [1, -2],
    [0, 4]
])

B = np.array([
    [4, -1],
    [1, 1]
])


m, n = A.shape

# Define variables
pi = cp.Variable((m, n), nonneg=True)

# Constraints
constraints = [cp.sum(pi) == 1]

for i in range(m):
    for i_prime in range(m):
        if i != i_prime:
            constraints.append(cp.sum(pi[i, :] * (A[i, :] - A[i_prime, :])) >= 0)

for j in range(n):
    for j_prime in range(n):
        if j != j_prime:
            constraints.append(cp.sum(pi[:, j] * (B[:, j] - B[:, j_prime])) >= 0)

# Define the objective function (maximize the sum of expected payoffs)
objective = cp.Maximize(cp.sum(cp.multiply(pi, A + B)))

# Solve the problem
problem = cp.Problem(objective, constraints)
problem.solve()

print("Correlated Equilibrium joint distribution (non-zero-sum):")
print(pi.value)

Correlated Equilibrium joint distribution (non-zero-sum):
[[0.59103276 0.        ]
 [0.         0.40896724]]


C:\Users\Mazi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cvxpy\expressions\expression.py:650: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 9 times so far.

  warnings.warn(msg, UserWarning)
C:\Users\Mazi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\cvxpy\expressions\expression.py:650: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-mat