In [95]:
import numpy as np
import NormalFormGames

In [96]:

game_of_chicken_row = np.array([[2, -2],
                            [4, -20]])

game_of_chicken_col = np.array([[2, 4],
                            [-2, -20]])

game = NormalFormGames.NormalFormGameCalculator(game_of_chicken_row, game_of_chicken_col)

exploitabilities = game.regret_minimization(game_of_chicken_row, game_of_chicken_col, 10)

import matplotlib.pyplot as plt

exploitabilities

([array([0.5, 0.5]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([0.66666667, 0.33333333]),
  array([0.5, 0.5]),
  array([0.35, 0.65]),
  array([0.17032967, 0.82967033]),
  array([0., 1.]),
  array([0., 1.])],
 [array([0.5, 0.5]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.])],
 array([-4.62600733,  5.37399267]),
 array([   7.        , -129.26007326]),
 [array([ 4., -4.]),
  array([4., 6.]),
  array([2., 4.]),
  array([0., 2.]),
  array([-2.66666667, -0.66666667]),
  array([-5.66666667, -3.66666667]),
  array([-8.96666667, -6.96666667]),
  array([-12.62600733, -10.62600733]),
  array([-16.62600733, -14.62600733]),
  array([-20.62600733, -18.62600733])],
 [array([ 7., -7.]),
  array([4., 0.]),
  array([ 2., -2.]),
  array([ 0., -4.]),
  array([ -2.        , -12.66666667]),
  array([ -4.66666667, -18.66666667]),
  array([ -7.66666667, -24.666666